services:
  database:
    hostname: postgres
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/volumes/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
        
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
